Fix

diff --git a/.github/workflows/builtAndTest.yml b/.github/workflows/builtAndTest.yml
--- a/.github/workflows/builtAndTest.yml
+++ b/.github/workflows/builtAndTest.yml
@@ -95,6 +95,11 @@ jobs:
       - name: Rename PcapPlusPlus directory
         run: |
           export RELEASE_DIR=$(find "$GITHUB_WORKSPACE/server/linux/libs" -maxdepth 1 -type d -name 'pcapplusplus*' | head -n 1)
+          if [ -z "$RELEASE_DIR" ]; then
+            echo "Error: No directory matching 'pcapplusplus*' found."
+            exit 1
+          fi
+          echo $RELEASE_DIR
           mv $RELEASE_DIR $GITHUB_WORKSPACE/server/linux/libs/pcapplusplus
 
       - name: Build VPN server
